import "./globals.css";
import type { Metadata } from "next";
import { SITE_NAME, SITE_URL, SITE_ICO, fonts } from "@/data/config";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
    title: {
        default: SITE_NAME,
        // 用在子页面的标题
        template: `%s | ${SITE_NAME}`,
    },
    description: "Generated by Ling",
    generator: "Next.js",
    keywords: ["Blog", "AI", "ML"],
    authors: [
        { name: "Ling Yu" },
        { name: "NextJs", url: "https://nextjs.org" },
    ],
    openGraph: {
        title: SITE_NAME,
        description: "Developer and Writer.",
        url: SITE_URL,
        siteName: SITE_URL,
        locale: "zh-CN",
        type: "website",
        images: [],
    },
    icons: {
        //app目录下无favicon.ico，此处才会生效
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="zh-CN"
            className={`flex flex-col h-full ${fonts.className}`}
        >
            <body
                suppressHydrationWarning={true}
                className="flex flex-col h-full px-2"
            >
                <Providers>
                    <Navbar />
                    <main className="text-black dark:text-white mx-0 px-2 py-0 flex-1 leading-6 justify-center">
                        {children}
                    </main>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
